spring.application.name=WeatherPrediction
server.port=8080
weather.api.url=${WEATHER_API_URL:https://api.openweathermap.org/data/2.5/forecast}
weather.api.key=${OPENWEATHER_API_KEY:}
springdoc.swagger-ui.path=/swagger-ui.html
server.error.include-message=never
server.shutdown=graceful
